sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    bucket-name: javaweb-course
    access-key-id: LTAI5tJu5vJJ2mK2Qsc8ZsGU
    access-key-secret: nr8RBRWVcB2gPRXphbSJc9G4NpIc4O
  redis:
    host: localhost
    port: 6379
    database: 10
    password: 123456
  wechat:
    appid: wx0558df48f55095fd
    secret: 26d1bb53b970a72de96d3d712e585c28

